/*=================================================================
 *
 * MATRIXDRIVER.C	Sample driver code that calls the shared
 *	library created using MATLAB Compiler. Refer to the 
 *  documentation of MATLAB Compiler for more information on
 *  this
 *
 * This is the wrapper C code to call a shared library created 
 * using MATLAB Compiler.
 *
 * Copyright 1984-2000 The MathWorks, Inc.
 *
 *=================================================================*/

#include <stdio.h>
#include <pthread.h>
#include <sys/time.h>

double getwtime()
{
	struct timeval t;
	gettimeofday(&t, NULL);
	return (double)t.tv_sec + (double)t.tv_usec*1.0E-6;
}


/* Include the MCR header file and the library specific header file 
 * as generated by MATLAB Compiler */
#include "mclmcr.h" 
#include "libmatrix.h"

/* This function is used to display a double matrix stored in an mxArray */
void display(const mxArray* in);

pthread_mutex_t cs = PTHREAD_MUTEX_INITIALIZER;

mxArray *in1, *in2; /* Define input parameters */
mxArray *out = NULL;/* and output parameters to be passed to the library functions */

void *ThreadOne(void *lpParam)
{
	mxArray *out = NULL;/* and output parameters to be passed to the library functions */

	printf("Hello from thread %ld\n", *((long *)lpParam));

	/* Call the library function */
	mlfAddmatrix(1, &out, in1, in2);
	/* Display the return value of the library function */
	pthread_mutex_lock(&cs);
	printf("The value of added matrix is:\n");
	display(out);
	pthread_mutex_unlock(&cs);
	mxDestroyArray(out); out=0;

	return 0;
}

void *ThreadTwo(void *lpParam)
{
	mxArray *out = NULL;/* and output parameters to be passed to the library functions */

	printf("Hello from thread %ld\n", *((long *)lpParam));

	mlfMultiplymatrix(1, &out, in1, in2);
	pthread_mutex_lock(&cs);
	printf("The value of the multiplied matrix is:\n");
	display(out);
	pthread_mutex_unlock(&cs);
	mxDestroyArray(out); out=0;

	return 0;
}


void *ThreadThree(void *lpParam)
{
	mxArray *out = NULL;/* and output parameters to be passed to the library functions */

	printf("Hello from thread %ld\n", *((long *)lpParam));

	mlfEigmatrix(1, &out, in1);
	pthread_mutex_lock(&cs);
	printf("The Eigen value of the first matrix is:\n");
	display(out);
	pthread_mutex_unlock(&cs);
	mxDestroyArray(out); out=0;
}

int main(){
	double t1, t2;
	pthread_t hThread[3];
	long dwID[3];
	long dwRetVal;

	double data[] = {1,2,3,4,5,6,7,8,9};

	t1 = getwtime();
	if( !mclInitializeApplication(NULL,0) )
	{
		fprintf(stderr, "Could not initialize the application.\n");
		exit(1);
	}
	t2 = getwtime();
	printf("Initialization: %d msec\n", t2-t1);

	/* Create the input data */
	t1 = getwtime(); 
	in1 = mxCreateDoubleMatrix(3,3,mxREAL);
	in2 = mxCreateDoubleMatrix(3,3,mxREAL);
	memcpy(mxGetPr(in1), data, 9*sizeof(double));
	memcpy(mxGetPr(in2), data, 9*sizeof(double));
	t2 = getwtime(); 
	printf("Create input data: %d msec\n", t2-t1);

	/* Call the library intialization routine and make sure that the
	 * library was initialized properly. */

	t1 = getwtime();
	if (!libmatrixInitialize()){
		fprintf(stderr,"Could not initialize the library.\n");
		exit(1);
	}
	t2 = getwtime();

	printf("Library initialization: %d msec\n", t2-t1);

	dwID[0] = 0;
	dwID[1] = 1;
	dwID[2] = 2;
	pthread_create(&hThread[0], NULL, ThreadOne, &dwID[0]);
	pthread_create(&hThread[1], NULL, ThreadTwo, &dwID[1]);
	pthread_create(&hThread[2], NULL, ThreadThree, &dwID[2]);

	pthread_join(hThread[0], NULL);
	pthread_join(hThread[1], NULL);
	pthread_join(hThread[2], NULL);

	/* Call the library termination routine */
	libmatrixTerminate();

	/* Free the memory created */
	mxDestroyArray(in1); in1=0;
	mxDestroyArray(in2); in2 = 0;
	mclTerminateApplication();
	return 0;
}


/*DISPLAY This function will display the double matrix stored in an mxArray.
 * This function assumes that the mxArray passed as input contains double
 * array.
 */
void display(const mxArray* in)
{
	int i=0, j=0; /* loop index variables */
	int r=0, c=0; /* variables to store the row and column length of the matrix */
	double *data; /* variable to point to the double data stored within the mxArray */

	/* Get the size of the matrix */
	r = mxGetM(in);
	c = mxGetN(in);
	/* Get a pointer to the double data in mxArray */
	data = mxGetPr(in);

	/* Loop through the data and display the same in matrix format */
	for( i = 0; i < c; i++ ){
		for( j = 0; j < r; j++){
			printf("%4.2f\t",data[i*c+j]);
		}
		printf("\n");
	}
	printf("\n");
}
