/*=================================================================
 *
 * MATRIXDRIVER.C	Sample driver code that calls the shared
 *	        library created using MATLAB Compiler. Refer to the 
 *          documentation of MATLAB Compiler for more information on
 *          this
 *
 * This is the wrapper C code to call a shared library created 
 * using MATLAB Compiler.
 *
 * Copyright 1984-2000 The MathWorks, Inc.
 *
 *=================================================================*/

#include <stdio.h>

/* Include the MCR header file and the library specific header file 
 * as generated by MATLAB Compiler */
#include "mclmcr.h" 
#include "libprime.h"

/* This function is used to display the primes stored in an mxArray */
void display_vector(const mxArray* in);

int main(){
    
    mxArray *in1; /* Define input parameters */
    mxArray *out = NULL;/* and output parameters to be passed to the library functions */
	double data = 6;
    

    /* Call the mclInitializeApplication routine. Make sure that the application
     * was initialized properly by checking the return status. This initialization
     * has to be done before calling any MATLAB API's or MATLAB Compiler generated
     * shared library functions.  */
    if( !mclInitializeApplication(NULL,0) )
    {
        fprintf(stderr, "Could not initialize the application.\n");
        exit(1);
    }
    
    /* Create the input data */
    in1 = mxCreateDoubleMatrix(1,1,mxREAL);
    memcpy(mxGetPr(in1), &data, 1*sizeof(double));
    
    /* Call the library intialization routine and make sure that the
     * library was initialized properly. */
    if (!libprimeInitialize()){
        fprintf(stderr,"Could not initialize the library.\n");
        exit(1);
    }

    /* Call the library function */
    mlfCallprimes(1, &out, in1);
    /* Display the return value of the library function */
    printf("The vector of primes is:\n");
    display_vector(out);
    /* Destroy the return value since this varaible will be resued in
     * the next function call. Since we are going to reuse the variable,
     * we have to set it to NULL. Refer to MATLAB Compiler documentation
     * for more information on this. */
    mxDestroyArray(out); out=0;
    
    /* Call the library termination routine */
    libprimeTerminate();
    
    /* Free the memory created */
    mxDestroyArray(in1); in1=0;
    mclTerminateApplication();
    return 0;
}


void display_vector(const mxArray* in)
{
    int i=0, j=0; /* loop index variables */
    int r=0, c=0; /* variables to store the row and column length of the matrix */
    double *data; /* variable to point to the double data stored within the mxArray */

    /* Get the size of the matrix */
    r = mxGetM(in);
    c = mxGetN(in);

    /* Get a pointer to the double data in mxArray */
    data = mxGetPr(in);
    
    /* Loop through the data and display the same in matrix format */
    for( i = 0; i < c; i++ ){
		printf("%4.2f\t",data[i]);
    }
    printf("\n");
}
